#!/bin/bash
rm *.tmp cookie > /dev/null

# This script works as of 20240108 This script is for exporting CSV for Trained Leaders Status and Your Protection YPT Status Report. You replace the freeload101 with your username and ___YOURPASSWORD____ with your password as for the rest the OrganizationGUID and  SessionGUID they will need to be pulled by looking at the source code. There may be other things that need to be changed but they are really only just the file name I don't they it matters.

echo `date` DEBUG: login lulz cuz Capcha is optional

curl -s --compressed -b cookie -c cookie  -k -X $'POST' -H $'Host: my.scouting.org' -H $'Content-Length: 28' -H $'Sec-Ch-Ua: \"(Not(A:Brand\";v=\"8\", \"Chromium\";v=\"98\"' -H $'Accept: application/json; version=2' -H $'Content-Type: application/json' -H $'Sec-Ch-Ua-Mobile: ?0' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36' -H $'Sec-Ch-Ua-Platform: \"Windows\"' -H $'Origin: https://my.scouting.org' -H $'Sec-Fetch-Site: same-origin' -H $'Sec-Fetch-Mode: cors' -H $'Sec-Fetch-Dest: empty' -H $'Referer: https://my.scouting.org/' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en-US,en;q=0.9' -H $'Connection: close' --data-binary $'{\"password\":\"___YOURPASSWORD____^\"}' $'https://my.scouting.org/api/users/freeload101/authenticate' >> log.log

echo `date` DEBUG: Getting TrainedLeadersStatus ContextToken

VAR_CTOKEN=`curl -b cookie -b cookie -s -k -X $'GET' -H $'Host: my.scouting.org' -H $'Sec-Ch-Ua: \"(Not(A:Brand\";v=\"8\", \"Chromium\";v=\"98\"' -H $'Sec-Ch-Ua-Mobile: ?0' -H $'Sec-Ch-Ua-Platform: \"Windows\"' -H $'Upgrade-Insecure-Requests: 1' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H $'Sec-Fetch-Site: same-origin' -H $'Sec-Fetch-Mode: navigate' -H $'Sec-Fetch-User: ?1' -H $'Sec-Fetch-Dest: document' -H $'Referer: https://my.scouting.org/legacy/' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en-US,en;q=0.9' -H $'Connection: close' $'https://my.scouting.org//mystrpt/webreport/output/?method=loadreportpage&reportcode=TrainedLeadersStatus2&OrganizationGUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXX&SessionGUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXX&ToolName=Trained%20Leader%20Report&IsStaff=0' | grep -iPo '(?<=ContextToken=).*(?=\&amp)'`


echo `date` DEBUG: Saving TrainedLeadersStatus output
curl -b cookie -b cookie -s -k -X $'GET' -H $'Host: my.scouting.org' -H $'Sec-Ch-Ua: \"(Not(A:Brand\";v=\"8\", \"Chromium\";v=\"98\"' -H $'Sec-Ch-Ua-Mobile: ?0' -H $'Sec-Ch-Ua-Platform: \"Windows\"' -H $'Upgrade-Insecure-Requests: 1' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H $'Sec-Fetch-Site: same-origin' -H $'Sec-Fetch-Mode: navigate' -H $'Sec-Fetch-User: ?1' -H $'Sec-Fetch-Dest: document' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en-US,en;q=0.9' -H $'Connection: close' "https://my.scouting.org/mystrpt/webreport/output/proxy.aspx?Method=CreateReportFileOutputFromContext&ContextToken=${VAR_CTOKEN}&ExportFileName=TrainedLeader_Pack_0450__NORTHMINSTER_PRESBYTERIAN_CHURCH.csv&OutputFormat=@Download@TEXT&ColumnList=CouncilName,SubCouncil,ServiceArea,District,SubDistrict,UnitName,GenderAccepted,ChartedOrganization,FirstName,MiddleName,LastName,Zip5,MemberID,ProgramName,EmailAddress,PositionName,IsDirectContactLeader,IsPositionTrained2,RegistrationExpiryDateStr,NotCompletedCourseList0,NotCompletedCourseList1,NotCompletedCourseList2,NotCompletedCourseList2_Part1,NotCompletedCourseList2_Part2" > Trained_Leaders_Status.tmp

#grep -E "\bNO\b|Council," Trained_Leaders_Status.tmp


echo `date` DEBUG: Getting YPTStatusReport ContextToken
VAR_CTOKEN=`curl -b cookie -b cookie -s -k -X $'GET' -H $'Host: my.scouting.org' -H $'Sec-Ch-Ua: \"(Not(A:Brand\";v=\"8\", \"Chromium\";v=\"98\"' -H $'Sec-Ch-Ua-Mobile: ?0' -H $'Sec-Ch-Ua-Platform: \"Windows\"' -H $'Upgrade-Insecure-Requests: 1' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H $'Sec-Fetch-Site: same-origin' -H $'Sec-Fetch-Mode: navigate' -H $'Sec-Fetch-User: ?1' -H $'Sec-Fetch-Dest: document' -H $'Referer: https://my.scouting.org/legacy/' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en-US,en;q=0.9' -H $'Connection: close' $'https://my.scouting.org//mystrpt/webreport/output/?method=loadreportpage&reportcode=YPTStatusReport&OrganizationGUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXX&&SessionGUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXX&&ToolName=Training%20Manager&IsStaff=0&ParentOnlyFlag=1' | grep -iPo '(?<=ContextToken=).*(?=\&amp)'`


curl -b cookie -b cookie -s -k -X $'GET' -H $'Host: my.scouting.org' -H $'Sec-Ch-Ua: \"(Not(A:Brand\";v=\"8\", \"Chromium\";v=\"98\"' -H $'Sec-Ch-Ua-Mobile: ?0' -H $'Sec-Ch-Ua-Platform: \"Windows\"' -H $'Upgrade-Insecure-Requests: 1' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H $'Sec-Fetch-Site: same-origin' -H $'Sec-Fetch-Mode: navigate' -H $'Sec-Fetch-User: ?1' -H $'Sec-Fetch-Dest: document'  "https://my.scouting.org/mystrpt/webreport/output/proxy.aspx?Method=CreateReportFileOutputFromContext&ContextToken=${VAR_CTOKEN}&ExportFileName=YPT_Pack_0450__NORTHMINSTER_PRESBYTERIAN_CHURCH.csv&OutputFormat=@Download@TEXT&ColumnList=Council,District,SubDistrict,UnitType,UnitNumber,GenderAccepted,ChartedOrganization,FirstName,MiddleName,LastName,MemberID,PositionName,IsYPTCurrent2,YPTExpirationDateC,Y01CourseCode,Y01CompletionDateC,Y01ExpirationDateC,Y02CourseCode,Y02CompletionDateC,Y02ExpirationDateC,Y03CourseCode,Y03CompletionDateC,Y03ExpirationDateC,EmailAddress,PhoneNumber,RegistrationDateC,strOnlineCourses" > YPTStatusReport.tmp

echo `date` DEBUG: Saving YPTStatusReport output

grep -A 999 '..District,' YPTStatusReport.tmp > YPTStatus_n_Trained_Leaders.csv
grep -vE "(\"YES\",\"YES\")" Trained_Leaders_Status.tmp | grep -A 9999 "^Council," >> YPTStatus_n_Trained_Leaders.csv
